### ISSUE TITLE
Can you also do the Winform Version as well please ?

### ISSUE THREAD

**Issue by Smurf-IV** [Weingartner/eyeshot#1]
From V 12.0.## onwards

![image](https://user-images.githubusercontent.com/2418812/112970082-bd527200-9145-11eb-8493-52d1848e5af7.png)

**Comment by JKronberger** [comment]
Sorry, we only have a valid Eyeshot.WPF license. So we can't provide the Winforms version.

**Comment by Smurf-IV** [comment]
I didn't think the license had anything to do with the installed files.. i.e. you can still install them, just not use them unless the developer has personaly got a valid license.

**Comment by FlorianAuinger** [comment]
from v2023 onwards the winforms dll is now included in the [devDept.Eyeshot.WinForms](https://www.nuget.org/packages/devDept.Eyeshot.WinForms) package
